source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

gem 'rails', '~> 6.0.3', '>= 6.0.3.2'
gem 'rails-i18n', '~> 6.0.0'
gem 'mysql2', '>= 0.4.4'
gem 'unicorn'
gem 'unicorn-worker-killer'
gem 'puma', '~> 4.1'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'rjb'
gem 'zipang'
gem 'romkan'
gem 'sidekiq'
gem 'redis-rails'
gem 'redis-namespace'
gem 'line-bot-api'
gem 'line_message_creator'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  gem 'pry-rails'
  gem 'pry-doc'
  gem 'pry-remote'
  gem 'pry-byebug'
  gem 'rails-erd'
  gem 'brakeman'
end

group :development do
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'rubocop', require: false
end

group :test do
  gem 'faker'
  gem 'rspec-rails'
  gem 'rspec-sidekiq'
  gem 'spring-commands-rspec'
  gem 'factory_bot_rails'
  gem 'database_cleaner'
  gem 'rails-controller-testing'
  gem 'bullet'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
